// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU_t-JkZ1lodpHzVpd30v8DXSB1bdM1DQ',
    appId: '1:97367838719:web:ed60ada95f8f1c428021ca',
    messagingSenderId: '97367838719',
    projectId: 'twitter-ztm-3ba12',
    authDomain: 'twitter-ztm-3ba12.firebaseapp.com',
    storageBucket: 'twitter-ztm-3ba12.appspot.com',
    measurementId: 'G-CB80SGEN16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoUio7y8uWJpNNOIJ6xtgXyfHX0IMuQ-k',
    appId: '1:97367838719:android:a8c6555f29f5310e8021ca',
    messagingSenderId: '97367838719',
    projectId: 'twitter-ztm-3ba12',
    storageBucket: 'twitter-ztm-3ba12.appspot.com',
  );
}
