// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_unovK8xW0oJkWQL4kxQqFZx_LCHqbo',
    appId: '1:762731763702:web:d7b91cf1bfd1d4064859d7',
    messagingSenderId: '762731763702',
    projectId: 'flutter-ztm-1cc18',
    authDomain: 'flutter-ztm-1cc18.firebaseapp.com',
    storageBucket: 'flutter-ztm-1cc18.appspot.com',
    measurementId: 'G-G1BQQV2JR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzMyilRU33HKrxfAnwEdhnOlULMx3ZTc',
    appId: '1:762731763702:android:934d37b234a132f54859d7',
    messagingSenderId: '762731763702',
    projectId: 'flutter-ztm-1cc18',
    storageBucket: 'flutter-ztm-1cc18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_AecirDcogmJg9FWp9OADQER452L80n0',
    appId: '1:762731763702:ios:89692785eda0a5304859d7',
    messagingSenderId: '762731763702',
    projectId: 'flutter-ztm-1cc18',
    storageBucket: 'flutter-ztm-1cc18.appspot.com',
    iosBundleId: 'com.example.flutterZtm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_AecirDcogmJg9FWp9OADQER452L80n0',
    appId: '1:762731763702:ios:89692785eda0a5304859d7',
    messagingSenderId: '762731763702',
    projectId: 'flutter-ztm-1cc18',
    storageBucket: 'flutter-ztm-1cc18.appspot.com',
    iosBundleId: 'com.example.flutterZtm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM_unovK8xW0oJkWQL4kxQqFZx_LCHqbo',
    appId: '1:762731763702:web:8daa397b367e95514859d7',
    messagingSenderId: '762731763702',
    projectId: 'flutter-ztm-1cc18',
    authDomain: 'flutter-ztm-1cc18.firebaseapp.com',
    storageBucket: 'flutter-ztm-1cc18.appspot.com',
    measurementId: 'G-LLHRQGK0P8',
  );

}